参考：

- http://www.cookbook-r.com/Graphs/Plotting_distributions_(ggplot2)/
- http://t-redactyl.io/blog/2016/04/creating-plots-in-r-using-ggplot2-part-10-boxplots.html

```{r}

```



```{r}
library(ggplot2)
mpg
p <- ggplot(mpg, aes(class, hwy))
p + geom_boxplot()
```

```{r}
p + geom_boxplot() + geom_jitter(width = 0.1)
```

```{r}
p + geom_boxplot() + coord_flip()
```

```{r}
p + geom_boxplot(notch = TRUE)
```

```{r}
p + geom_boxplot(varwidth = TRUE)
```

```{r}
p + geom_boxplot(fill = "steelblue", colour = "#3366FF")
```

```{r}
p + geom_boxplot(outlier.colour = "red", outlier.shape = 1)
```
#### Boxplots are automatically dodged when any aesthetic is a factor
```{r}
p + geom_boxplot(aes(colour = drv))
```

```{r}
head(diamonds)
ggplot(diamonds, aes(carat, price)) +
  geom_boxplot()
```

```{r}
ggplot(diamonds, aes(carat, price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.25)))
```



```{r}
ggplot(diamonds, aes(carat, price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.25)), outlier.alpha = 0.1)
```

```{r}
ggplot(mpg,aes(x=manufacturer,y=displ,fill=manufacturer))+geom_boxplot(outlier.shape = 19,outlier.size = 2,outlier.color ="red" )+
  labs(x="xlab is displ",y="ylab",title="title is manufacturer vs displ")+
  coord_flip()
```

```{r}
ggplot(mpg,aes(x=manufacturer,y=displ))+geom_boxplot(fill="steelblue",outlier.shape = 19,outlier.size = 2,outlier.color ="red" )+
  labs(x="xlab is displ",y="ylab",title="title is manufacturer vs displ")+
  coord_flip()
```

```{r}
ggplot(mpg,aes(x=manufacturer,y=displ))+geom_boxplot(fill="steelblue",varwidth=TRUE,outlier.shape = 19,outlier.size = 2,outlier.color ="red" )+
  labs(x="xlab is displ",y="ylab",title="title is manufacturer vs displ")+
  geom_hline(yintercept=4,color="red",linetype="dashed")+
  stat_summary(fun.y = "mean",geom="point",color="orange",size=2)
  
```

```{r}
mpg
```

```{r}
ggplot(mpg,aes(x=displ,color=manufacturer))+geom_density()
```



```{r}
ggplot(mpg,aes(x=displ,color=manufacturer))+geom_density()+facet_wrap("fl")
```

```{r}
ggplot(mpg,aes(x=displ,color=manufacturer))+geom_density()+facet_grid(drv~fl)
```

```{r}
ggplot(mpg,aes(x=displ,y=cty,shape=fl))+geom_point()
```

```{r}
ggplot(diamonds, aes(x=carat, y=price, color=depth)) +geom_point()+scale_color_gradient(low="white",high = "royalblue")      #steelblue
```

```{r}
ggplot(diamonds, aes(x=carat, y=price, color=clarity)) + geom_point() + scale_color_brewer(palette = 1)
```

```{r}
diamonds
```

```{r}
ggplot(diamonds, aes(x=price)) + geom_histogram(colour="steelblue")
```

```{r}
ggplot(diamonds, aes(x=price, color=clarity)) + geom_density()+theme_bw()
```

```{r}
ggplot(diamonds, aes(x=price, color=clarity)) + geom_density()+theme_light()
```

```{r}
ggplot(diamonds, aes(x=clarity))+geom_bar()
```

```{r}
set.seed(1234)
dat <- data.frame(cond = factor(rep(c("A","B"), each=200)), 
                   rating = c(rnorm(200),rnorm(200, mean=.8)))
# View first few rows
head(dat)
#>   cond     rating
#> 1    A -1.2070657
#> 2    A  0.2774292
#> 3    A  1.0844412
#> 4    A -2.3456977
#> 5    A  0.4291247
#> 6    A  0.5060559

# Histogram overlaid with kernel density curve
ggplot(dat , aes(x=rating)) + 
    geom_histogram(aes(y=..density..),      # Histogram with density instead of count on y-axis
                   binwidth=.5,
                   colour="black", fill="steelblue") +
    geom_density(alpha=.2)  # Overlay with transparent density plot
```

```{r}
# Overlaid histograms
ggplot(dat, aes(x=rating, fill=cond)) +
    geom_histogram(binwidth=.5, alpha=.5, position="identity")

# Interleaved histograms
ggplot(dat, aes(x=rating, fill=cond)) +
        geom_histogram(binwidth=.5, position="dodge")

# Stacked histograms
ggplot(dat, aes(x=rating, fill=cond)) +
        geom_histogram(binwidth=.5, position="stack")


# Density plots
ggplot(dat, aes(x=rating, colour=cond)) + geom_density()

# Density plots with semi-transparent fill
ggplot(dat, aes(x=rating, fill=cond)) + geom_density(alpha=.3)
```

```{r}
# Find the mean of each group
library(plyr)
cdat <- ddply(dat, "cond", summarise, rating.mean=mean(rating))
cdat
#>   cond rating.mean
#> 1    A -0.05775928
#> 2    B  0.87324927

# Overlaid histograms with means
ggplot(dat, aes(x=rating, fill=cond)) +
    geom_histogram(binwidth=.5, alpha=.5, position="identity") +
    geom_vline(data=cdat, aes(xintercept=rating.mean,  colour=cond),
               linetype="dashed", size=1)

# Density plots with means
ggplot(dat, aes(x=rating, colour=cond)) +
    geom_density() +
    geom_vline(data=cdat, aes(xintercept=rating.mean,  colour=cond),
               linetype="dashed", size=1)
```

```{r}
#Using facets:

ggplot(dat, aes(x=rating)) + geom_histogram(binwidth=.5, colour="black", fill="white") + 
    facet_grid(cond ~ .)

# With mean lines, using cdat from above
ggplot(dat, aes(x=rating)) + geom_histogram(binwidth=.5, colour="black", fill="white") + 
    facet_grid(cond ~ .) +
    geom_vline(data=cdat, aes(xintercept=rating.mean),
               linetype="dashed", size=1, colour="red")
```
```{r}
# A basic box plot
ggplot(dat, aes(x=cond, y=rating)) + geom_boxplot()

# A basic box with the conditions colored
ggplot(dat, aes(x=cond, y=rating, fill=cond)) + geom_boxplot()

# The above adds a redundant legend. With the legend removed:
ggplot(dat, aes(x=cond, y=rating, fill=cond)) + geom_boxplot() +
    guides(fill=FALSE)

# With flipped axes
ggplot(dat, aes(x=cond, y=rating, fill=cond)) + geom_boxplot() + 
    guides(fill=FALSE) + coord_flip()
```

```{r}
# Add a diamond at the mean, and make it larger
ggplot(dat, aes(x=cond, y=rating)) + geom_boxplot() +
    stat_summary(fun.y=mean, geom="point", shape=5, size=4)
```
```{r}
library(datasets)
data(airquality)

airquality_trimmed <- airquality[which(airquality$Month == 7 |
                                       airquality$Month == 8 |
                                       airquality$Month == 9), ]
airquality_trimmed$Temp.f <- factor(ifelse(airquality_trimmed$Temp > mean(airquality_trimmed$Temp), 1, 0),
                                    labels = c("Low temp", "High temp"))
p10 <- ggplot(airquality_trimmed, aes(x = factor(Month), y = Ozone, fill = Temp.f)) +
        geom_boxplot(alpha=0.7) +
        scale_y_continuous(name = "Mean ozone in\nparts per billion",
                           breaks = seq(0, 175, 25),
                           limits=c(0, 175)) +
        scale_x_discrete(name = "Month") +
        ggtitle("Boxplot of mean ozone by month") +
        theme_bw() +
        theme(plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
              text = element_text(size = 12, family = "Tahoma"),
              axis.title = element_text(face="bold"),
              axis.text.x=element_text(size = 11),
              legend.position = "bottom") +
        scale_fill_brewer(palette = "Accent") +
        labs(fill = "Temperature")
p10
```

```{r}
ggplot(diamonds, aes(x=price,fill="steelblue")) + geom_histogram()

ggplot(diamonds, aes(x=price)) + geom_histogram(fill="steelblue")
```


